name: Pipeline Simples

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Deploy simulado
        run: echo "Deploy realizado com sucesso!"
